# Generated by Django 2.1.1 on 2019-01-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=264)),
                ('Last_Name', models.CharField(max_length=264)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
